#!/usr/bin/env bash

set -e

rm -rf   ~/opt/maxima
mkdir -p ~/opt/maxima

curl -g -L -f -o ~/opt/maxima-common_5.42.2-1_all.deb https://fs.quyo.net/repl.it/klio/maxima-common_5.42.2-1_all.deb
curl -g -L -f -o ~/opt/maxima-sbcl_5.42.2-1_amd64.deb https://fs.quyo.net/repl.it/klio/maxima-sbcl_5.42.2-1_amd64.deb

dpkg -x ~/opt/maxima-common_5.42.2-1_all.deb ~/opt/maxima/
dpkg -x ~/opt/maxima-sbcl_5.42.2-1_amd64.deb ~/opt/maxima/

mv     ~/opt/maxima/usr/lib/x86_64-linux-gnu/maxima ~/opt/maxima/usr/lib
rm -rf ~/opt/maxima/usr/lib/x86_64-linux-gnu
