#!/usr/bin/env bash

set -e

[ -d $HOME/opt/maxima ] && exit 0

mkdir -p $HOME/opt/maxima

curl -g -L -f -o $HOME/opt/maxima-common_5.42.2-1_all.deb https://fs.quyo.net/repl.it/klio/maxima-common_5.42.2-1_all.deb
curl -g -L -f -o $HOME/opt/maxima-sbcl_5.42.2-1_amd64.deb https://fs.quyo.net/repl.it/klio/maxima-sbcl_5.42.2-1_amd64.deb

dpkg -x $HOME/opt/maxima-common_5.42.2-1_all.deb ~/opt/maxima/
dpkg -x $HOME/opt/maxima-sbcl_5.42.2-1_amd64.deb ~/opt/maxima/

mv     $HOME/opt/maxima/usr/lib/x86_64-linux-gnu/maxima ~/opt/maxima/usr/lib
rm -rf $HOME/opt/maxima/usr/lib/x86_64-linux-gnu
